name: "CI/Nix"
on:
  workflow_call:

jobs:
  nix_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v17
        with:
          name: disk-spinner
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
      - uses: boinkor-net/ci-baseline-nix/actions/fmt@main
        with:
          root: "."
          skip_nix_setup: true

  nix_flake_safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v17
        with:
          name: disk-spinner
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
      - uses: boinkor-net/ci-baseline-nix/actions/flake_safety@main
        with:
          root: "."
          skip_nix_setup: true

  nix_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v17
        with:
          name: disk-spinner
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
      - uses: boinkor-net/ci-baseline-nix/actions/test@main
        with:
          root: "."
          skip_nix_setup: true

  build:
    strategy:
      matrix:
        derivation: [""]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v17
        with:
          name: disk-spinner
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
      - uses: boinkor-net/ci-baseline-nix/actions/build@main
        with:
          root: "."
          installable: ${{matrix.derivation}}
          skip_nix_setup: true
